" Incarntion P. Lee personal vim configuration file.
" Create at: Fri Jan  8 21:25:53 CST 2016
syntax on

set nocompatible                 " Disable the compatible for vi
set showcmd		         " Show (partial) command in status line.
set showmatch                    " Show matching brackets.
set smartcase		         " Do smart case matching
set incsearch                    " Incremental search
set cursorline                   " show a underline at current line
set nu
set nowrap                       " disable new line
set noswapfile                   " do not generate .swp file
set cursorcolumn
set ruler
set hls
set scrolloff=3
set matchtime=1
set magic
set laststatus=2
set t_Co=256                     " use 256 color in vim
set background=dark
set shell=bash
set completeopt=longest,menu
set backspace=start
set statusline=%<%f\ %h%m%r%=%k[%{(&fenc==\"\")?&enc:&fenc}%{(&bomb?\",BOM\":\"\")}]\ %-14.(%l,%c%V%)\ %P
set foldmethod=marker            " zf% mark pair () [] {}

highlight CursorColumn ctermbg=235
highlight Pmenu ctermbg=darkgrey ctermfg=black
highlight PmenuSel ctermbg=lightgrey ctermfg=blue

" Auto jump to the line when last exiting file
autocmd BufReadPost *
   \ if line("'\"") > 0 && line("'\"") <= line("$") |
   \     exe "normal g'\"" |
   \ endif

" Plugin for vim
" Tagbar
let g:tagbar_width=25
nmap <F9> :TagbarToggle<CR>

" NERD_tree
" nmap <F10> :NERDTreeMirror<CR>
nmap <silent> <F10> :NERDTreeToggle<CR>
let g:NERDTreeWinSize=20
let g:NERDTreeWinPos='left'
let g:NERDChristmasTree=1

" Ctrlp
set runtimepath^=~/.vim/bundle/ctrlp.vim

